/*
 * Generated from the source schema by scripts/generate-source-types.ts.
 * Do not edit this file manually.
 */

/**
 * Codex rollout JSONL record (codex 0.129+ (codex-tui / Codex Desktop / codex_sdk_ts)). Every line is {timestamp, type, payload}. Drift is caught at record-type granularity: unknown top-level type or unknown event_msg/response_item payload type fails validation and is quarantined. Payload fields are intentionally lenient to avoid false quarantine on additive field drift.
 */
export type CodexV0_135Record = {
  [k: string]: unknown;
} & {
  type: "session_meta" | "turn_context" | "event_msg" | "response_item" | "compacted";
  payload?: unknown;
  [k: string]: unknown;
};
