import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const rootUrl = new URL("../", import.meta.url);
const pkgUrl = new URL("packages/source-schemas/", rootUrl);
const checkOnly = process.argv.includes("--check");

const agents = ["codex", "pi", "claude-code", "opencode"];
let stale = false;

for (const agent of agents) {
  const agentUrl = new URL(`${agent}/`, pkgUrl);
  const entries = await readdir(agentUrl);
  const schemaFiles = entries.filter((name) => name.endsWith(".json") && name !== "meta.json");

  for (const file of schemaFiles) {
    const schemaUrl = new URL(file, agentUrl);
    const schema = JSON.parse(await readFile(schemaUrl, "utf8"));
    const typeName = typeof schema.title === "string" ? schema.title : `${agent}Record`;
    const compiledType = await compile(schema, typeName, {
      bannerComment:
        "/*\n * Generated from the source schema by scripts/generate-source-types.ts.\n * Do not edit this file manually.\n */",
      additionalProperties: true,
      style: {
        bracketSpacing: true,
        printWidth: 100,
        semi: true,
        singleQuote: false,
        tabWidth: 2,
        trailingComma: "all",
        useTabs: false,
      },
    });
    const compiled = `${compiledType}\ndeclare const schema: Record<string, unknown>;\nexport default schema;\n`;

    const outputUrl = new URL(file.replace(/\.json$/, ".d.ts"), agentUrl);
    if (checkOnly) {
      const existing = await readFile(outputUrl, "utf8").catch(() => "");
      if (existing !== compiled) {
        console.error(`${fileURLToPath(outputUrl)} is stale. Run bun run generate:source-types.`);
        stale = true;
      }
    } else {
      await writeFile(outputUrl, compiled);
    }
  }
}

if (stale) {
  process.exit(1);
}
