/*
 * Generated from the source schema by scripts/generate-source-types.ts.
 * Do not edit this file manually.
 */

/**
 * OpenCode normalized storage record. Covers SQLite rows and file-storage JSON normalized by the adapter into session, message, part, todo, session_message, permission, and event records. Drift is caught at record-type and part-type granularity; additive fields remain lenient.
 */
export type OpenCodeV1Record = {
  [k: string]: unknown;
} & {
  type:
    | "session"
    | "project"
    | "message"
    | "part"
    | "todo"
    | "session_message"
    | "permission"
    | "event";
  part_type?:
    | "text"
    | "reasoning"
    | "tool"
    | "step-start"
    | "step-finish"
    | "snapshot"
    | "patch"
    | "agent"
    | "retry"
    | "compaction"
    | "subtask"
    | "file";
  [k: string]: unknown;
};

declare const schema: Record<string, unknown>;
export default schema;
